### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by ibuilder** [zhengjinhua/XLSX2JSON#1]
Is there more of a description on how to make this work/use it?

It looks really awesome

**Comment by zhengjinhua** [comment]
ths for your suggestion

USAGE directory:

php config.php --path=data --check

php config.php --path=data --dump

file:

php config.php --path=data/test.xlsx --dump

php config.php --path=data/test.xlsx --check

excel file formation

line 1 : column description

line 2 : column type int/string

line 3 : column scope int scope/string length

line 4 : column relative relative another file's column

line 5 : column name json key

see data/test.xlsx
